---
- name: Install MySQL and PyMySQL
  become: yes
  apt:
    pkg:
      - mysql-server
      - python3-pymysql
    state: latest

# データベースの作成
- name: Create MySQL database
  ansible.mysql.mysql_db:    # community.mysql.mysql_db から変更
    name: test
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

# アプリ用ユーザーの作成と権限付与
- name: Create MySQL application user
  ansible.mysql.mysql_user:  # community.mysql.mysql_user から変更
    name: intern
    password: "password"
    priv: 'test.*:ALL'
    host: 'localhost'
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
